### ISSUE TITLE
SignUp 페이지 에러 처리 이슈

### ISSUE THREAD

**Issue by nayeon-hub** [prgrms-fe-devcourse/FEDC4_NIRVANA_Gidong#104]
회원가입 버튼을 눌렀는데, 에러가 발생함 -> 모달 창 켜짐 -> 모달 창 끄고 다시 회원가입 버튼을 누르면 모달 창이 켜지지 않습니다! 

아마도 alert 내부에서도 alert on/off에 대한 상태 관리가 이루어져서 그런 것 같습니다.

@sgd122 alert 내부에서 상태 관리로 인한 side effect가 생기는 것 같은데 개선이 필요할 것 같습니다!

**Comment by imb96** [comment]
PR#101 에서 처리해서 push했습니다.
