### ISSUE TITLE
Posts 스크롤 오류

### ISSUE THREAD

**Issue by imb96** [prgrms-fe-devcourse/FEDC4_NIRVANA_Gidong#106]
포스트가 많을 때 아래로 스크롤하면 위에있던 포스트가 사라집니다.
현재 불안 채널에서 확인 해볼 수 있습니다.

**Comment by suyeon1218** [comment]
해당 오류를 수정한 PR 를 뒤늦게 merge 했습니다. 이제 정상적으로 동작하리라 생각이 듭니당
