### ISSUE TITLE
Meditation UI오류 수정 요청

### ISSUE THREAD

**Issue by hyesung99** [prgrms-fe-devcourse/FEDC4_NIRVANA_Gidong#77]
1. 0.35분이 아닌 가운데 명상버튼과 같은 형식으로 시간을 표시해주세요
+선택 요청사항 아예 가운데 버튼 양쪽에 버튼을 달아서 시간을 설정할 수 있게 만들어주세요
![image](https://github.com/prgrms-fe-devcourse/FEDC4_NIRVANA_Gidong/assets/42764685/86b420ff-df53-47fb-a2b2-5fb704f7a3ee)

2. ~~시간 UI가 잘리는 문제~~
![image](https://github.com/prgrms-fe-devcourse/FEDC4_NIRVANA_Gidong/assets/42764685/2ef4c64e-650c-4a3d-b38f-87df93bad71e)

3. ~~ThemePicker UI 잘리는 듯한 느낌~~
![image](https://github.com/prgrms-fe-devcourse/FEDC4_NIRVANA_Gidong/assets/42764685/406badce-83df-435a-b34f-41fa47a31fdb)
~~에러는 아니지만 UI가 잘리는 듯한 느낌이 들어 어색한 것 같습니다.~~
~~화살표 background-image에 linear-gradiant로 opacity를 0에서 1로 증가시키면서 서서히 가리는 느낌으로 해주시면 좋을것 같습니다~~

**Comment by suyeon1218** [comment]
ThemePicker 는 제가 담당한 상태라 제가 처리해놓겠습니다!
