### ISSUE TITLE
Landing Page 중간 점검 이슈

### ISSUE THREAD

**Issue by suyeon1218** [prgrms-fe-devcourse/FEDC4_NIRVANA_Gidong#82]
### 🚨 명상 후기 보러가기

비로그인 회원들에게도 posts 는 접근 가능해야 하는데 로그인 요구 페이지가 뜨는 문제가 있습니다! 
    
### 👍🏻 회원 가입 시

바로 로그인할 수 있도록 세션 스토리지에 저장해놓는 기능이 완성도를 높일 수도 있을 거 같습니다!

**Comment by nayeon-hub** [comment]
로그인 요구 이슈는 라우팅 처리에서 해결하도록 하겠습니다!

**Comment by nayeon-hub** [comment]
posts 접근 가능하도록 완료했습니다!
