### ISSUE TITLE
Notice Page 중간 점검 이슈

### ISSUE THREAD

**Issue by suyeon1218** [prgrms-fe-devcourse/FEDC4_NIRVANA_Gidong#85]
### 🚨 알림
    
아직 알림 업데이트가 안 된 거겠지만 알림이 없는데 노란색 알람 뱃지가 보이는 문제가 있습니다!

**Comment by nayeon-hub** [comment]
맞습니다 구현되어서 PR 승인 후 머지하도록 하겠습니다!
