### ISSUE TITLE
Profile Page 중간 점검 이슈

### ISSUE THREAD

**Issue by suyeon1218** [prgrms-fe-devcourse/FEDC4_NIRVANA_Gidong#87]
### 🚨 ~~명상 뱃지가 잘리는 문제~~

![](https://file.notion.so/f/f/e937a7f9-dece-4540-8e1e-3c5966896424/794e010b-2789-4007-9aed-92587ae132ea/Untitled.png?id=3beab2fb-5de4-46e1-95c5-2306dafbe446&table=block&spaceId=e937a7f9-dece-4540-8e1e-3c5966896424&expirationTimestamp=1695542400000&signature=aZFKY6Q2AWOKqLXn3K_JZfKwFqz6uDqBlbvsmD7u2xM&downloadName=Untitled.png)

### 🎨 UI style 이 figma 와 맞지 않는 문제

![](https://file.notion.so/f/f/e937a7f9-dece-4540-8e1e-3c5966896424/54b06a6e-0f43-44b3-ab6b-fba12ff37563/Untitled.png?id=2e2ad717-4230-4bce-903f-ab85e8578372&table=block&spaceId=e937a7f9-dece-4540-8e1e-3c5966896424&expirationTimestamp=1695542400000&signature=YR2x7_hyI-N98XOC6SXqo7XmU_gWbKJ_xtyTq3oN3aY&downloadName=Untitled.png)

![](https://file.notion.so/f/f/e937a7f9-dece-4540-8e1e-3c5966896424/aa0948dc-eda2-4af9-b253-d7accbe3ce4c/Untitled.png?id=25b6236f-365d-4fe1-b908-9dce447ec723&table=block&spaceId=e937a7f9-dece-4540-8e1e-3c5966896424&expirationTimestamp=1695542400000&signature=Qo3ydqzOoUVdF4fRXR5GziaB4IDC0CXyq2-L0I5EdWc&downloadName=Untitled.png)

### 🎨 환경 설정 hover 가 글자에만 국한되는 문제

- 로그아웃에는 cursor CSS 가 적용되어 있지 않은 거 같아요
- 클릭시 hover 를 글자 뿐 아니라 칸 전체가 적용되면 편할 거 같아요
- hover 시 background-color 를 더 연한 회색으로 처리하면 좋을 거 같아요 (추후 추가)

![](https://file.notion.so/f/f/e937a7f9-dece-4540-8e1e-3c5966896424/f19dae60-d31a-4fa4-b9c3-ec8a010ae437/Untitled.png?id=98cd0752-87a0-4817-b128-410b346cc9ee&table=block&spaceId=e937a7f9-dece-4540-8e1e-3c5966896424&expirationTimestamp=1695542400000&signature=9Drex0X5C87g0C08hu4N3mL882NlujgmvZJRWZaLwYc&downloadName=Untitled.png)

### 🔨 환경 설정

- 저희가 DM 을 만들지 않을 거라면 환경 설정을 Header 로 옮겨버리는 게 좋을 거 같아요
- DM 아이콘도 삭제하고요!

### 👍🏻 작성된 포스트가 없는 경우

현재 작성된 포스트가 없다고 보여주면 좋을 거 같아요

**Comment by hyesung99** [comment]
🚨 명상 뱃지가 잘리는 문제 => 명상뱃지는 사용하지 않기로 해서 곧 삭제될 예정입니다!

**Comment by nayeon-hub** [comment]
헤더로 옮길까요 혜성님? 옮긴다면 헤더 디엠 버튼 삭제하면서 옮겨 놓겠습니다

**Comment by hyesung99** [comment]
디엠 버튼은 제가 삭제해서 PR올렸습니다!
저도 그렇게 생각해서 일단 환경설정 버튼은 냅뒀어요!

**Comment by hyesung99** [comment]
.
