### ISSUE TITLE
Login Page 중간 점검 이슈

### ISSUE THREAD

**Issue by suyeon1218** [prgrms-fe-devcourse/FEDC4_NIRVANA_Gidong#88]
### 👍🏻 로그아웃 시

- 로그아웃 시 정말 로그아웃 할 거냐고 묻는 Confirm 창 + 로그아웃이 정상적으로 처리되었다는 Alert 창이 있으면 좋을 거 같아요
- 로그아웃 시 바로 login 페이지로 이동하는 것보다 landing 페이지로 이동하는 것이 좋을 거 같아요!

### 로그인 시
![image](https://github.com/prgrms-fe-devcourse/FEDC4_NIRVANA_Gidong/assets/42764685/f7c00a96-2b22-4982-8f47-8d14a3d912d4)
자동완성으로 로그인 하지 못하는 에러 해결 부탁드립니다
현재 input value기반으로 로그인 하면 해결 가능해 보입니다.

**Comment by hyesung99** [comment]
해결완료했고 다른 자잘한 수정이랑 묶어서 PR 올리겠습니다!

**Comment by hyesung99** [comment]
로그아웃 시 바로 login 페이지로 이동하는 것보다 landing 페이지로 이동하는 것이 좋을 거 같아요!
=> 해결해서 PR올렸습니다!
