### ISSUE TITLE
Posts Page 중간 점검 이슈

### ISSUE THREAD

**Issue by suyeon1218** [prgrms-fe-devcourse/FEDC4_NIRVANA_Gidong#89]
### 👍🏻 작성된 포스트가 없는 경우
- 현재 작성된 포스트가 없다고 보여주면 좋을 거 같아요

**Comment by hyesung99** [comment]
이 문제 postDetail PR에서 해결해 놨습니다! 머지되면 수정될거에요!

**Comment by suyeon1218** [comment]
클릭시 잘못된 페이지로 이동하는 문제 말씀하시는 거죠?!

**Comment by hyesung99** [comment]
넵 맞습니다!
