### ISSUE TITLE
Search Page 중간 점검 이슈

### ISSUE THREAD

**Issue by suyeon1218** [prgrms-fe-devcourse/FEDC4_NIRVANA_Gidong#90]
### 🎨 UI 문제

- 사용자 정보 아이템에 padding-left 가 있었으면 좋겠어요
- 이름과 아이디 순서가 바뀐 거 같아요!
- SearchBar 가 살짝 왼쪽으로 치우친거 같아요!

<img width="412" alt="image" src="https://github.com/prgrms-fe-devcourse/FEDC4_NIRVANA_Gidong/assets/80307321/30058326-5b47-418b-8778-61a216077b7d">

**Comment by nayeon-hub** [comment]
아 그거 수정해서 PR 날렸어요~~!
