### ISSUE TITLE
SettingPage 로그아웃 이슈

### ISSUE THREAD

**Issue by nayeon-hub** [prgrms-fe-devcourse/FEDC4_NIRVANA_Gidong#97]
로그아웃 시 reload 함수가 실행되면
profile Page 재진입하게 되어 session storage에 값이 없는 것을 확인하고 login Page로 리다이랙트 되는 과정이 추가됩니다. 그리고 재로그인 시 이전에 진입했던 profile Page로 다시 리다이랙트 되구요!

이런 과정 없이 로그아웃 즉시 login Page로 이동하면 어떨까요?

**Comment by hyesung99** [comment]
의도하고 그렇게 만들었었는데 나연님이 말씀해주신 방식이 낫겠네요!

**Comment by nayeon-hub** [comment]
넵 로그아웃이 결국 이 서비스를 종료한다는 의미이기 떄문에 리다이랙트가 진행되지 않는 게 좋을 것 같습니다!

**Comment by hyesung99** [comment]
해결완료했고 다른 자잘한 수정이랑 묶어서 PR 올리겠습니다!
