### ISSUE TITLE
Login Page 로그인 경로 이슈

### ISSUE THREAD

**Issue by nayeon-hub** [prgrms-fe-devcourse/FEDC4_NIRVANA_Gidong#98]
로그인을 하지 않은 사용자가 로그인이 필요한 페이지로 이동하게 되면 로그인 페이지로 이동되는데요

이때, url에는 이전에 진입했던 페이지 정보가 들어있기 때문에 로그인 시 명상 페이지가 아닌 리다이랙트로 설정된 페이지로 이동해야해요!

**Comment by imb96** [comment]
해결해서 PR올렸습니다.
