### ISSUE TITLE
Footer 경로 이슈

### ISSUE THREAD

**Issue by nayeon-hub** [prgrms-fe-devcourse/FEDC4_NIRVANA_Gidong#99]
Footer에서 로그인을 하지 않은 채 명상 버튼을 누르면 로그인 페이지로 이동하도록 설정되어 있더라구요!
 
라우터에서 따로 처리해주고 있어서 Footer에서는 그대로 명상 페이지로 이동하셔도 됩니다~ (제가 라우팅 수정하면서 수정할까요?)

그리고 저희 로그인하지 않아도 명상 페이지 접근 가능하지 않나용?

**Comment by sscoderati** [comment]
비로그인 시 posts만 접근 가능한 걸로 알고 있습니다!
